# -*- coding: utf-8 -*-
"""netcdf_P.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZQe2U65UyG45e167DVVg9uqyoLkSs9c

**netCDF**

Usually We have to install netCDF4 in Google Collab and Jupyter Notebook for working on it.
"""

pip install netCDF4

import warnings
warnings.filterwarnings('ignore')

import datetime
import numpy as np
import netCDF4 as nc4

ncFileName = 'sample_netcdf.nc4'
modeType   = 'w'
fileFormat = 'NETCDF4'
ncfid = nc4.Dataset(ncFileName, mode=modeType, format=fileFormat)

"""This is just a Demo, If you need any help regarding your work or Project. Please **Email me vatshayan007@gmail.com **"""

